/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package univ.ml.distributed.coreset;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CoresetAlgorithm implements org.apache.thrift.TEnum {
  UNIFORM(0),
  NON_UNIFORM(1),
  KMEANS_PLUS_PLUS(2);

  private final int value;

  private CoresetAlgorithm(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CoresetAlgorithm findByValue(int value) { 
    switch (value) {
      case 0:
        return UNIFORM;
      case 1:
        return NON_UNIFORM;
      case 2:
        return KMEANS_PLUS_PLUS;
      default:
        return null;
    }
  }
}
